# Generated by Django 5.0.3 on 2024-03-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AfflictionType",
            fields=[
                (
                    "AfflictionType",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AfflictionType",
                "verbose_name_plural": "AfflictionType",
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "DomainName",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Employee Role",
                "verbose_name_plural": "Employee Role",
            },
        ),
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                (
                    "RoleName",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Employee Department",
                "verbose_name_plural": "Employee Department",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "MeetType",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Meeting Type",
                "verbose_name_plural": "Meeting Type",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "UnitName",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Customer Location",
                "verbose_name_plural": "Customer Location",
            },
        ),
        migrations.CreateModel(
            name="Affliction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=50)),
                ("Middlename", models.CharField(max_length=50)),
                ("Fullname", models.CharField(max_length=50)),
                ("Amount", models.CharField(max_length=7)),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("Date", models.DateField()),
                ("Report", models.FileField(null=True, upload_to="Affliction/")),
                (
                    "Incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.afflictiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affliction",
                "verbose_name_plural": "Affliction",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("PhoneNumber", models.CharField(max_length=15)),
                ("Email", models.CharField(max_length=150)),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True, null=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="Pending",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "AddressedTo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Android Customer Care",
                "verbose_name_plural": "Android Customer Care",
            },
        ),
        migrations.CreateModel(
            name="PhoneBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Position", models.CharField(max_length=250)),
                ("Phone1", models.CharField(max_length=12, null=True)),
                ("Phone2", models.CharField(max_length=12, null=True)),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True)),
                (
                    "Station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "PhoneBook",
                "verbose_name_plural": "PhoneBook",
            },
        ),
        migrations.CreateModel(
            name="Mahudhurio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CheckNumber", models.CharField(max_length=250)),
                ("MeetingDate", models.DateField()),
                ("Firstname", models.CharField(max_length=250)),
                ("MiddleName", models.CharField(max_length=250)),
                ("LastName", models.CharField(max_length=250)),
                ("PhoneNumber", models.CharField(max_length=250)),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True)),
                (
                    "MeetingType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.type"
                    ),
                ),
                (
                    "Unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Members Meeting",
                "verbose_name_plural": "Members Meeting",
            },
        ),
        migrations.CreateModel(
            name="WorkMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DateTime", models.DateTimeField()),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Weekly", "Weekly"),
                            ("Annually", "Annually"),
                            ("Daily", "Daily"),
                            ("Other", "Other"),
                        ],
                        max_length=250,
                    ),
                ),
                ("Report", models.FileField(upload_to="Meatings/")),
                ("RegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("LastUpdated", models.DateTimeField(auto_now=True)),
                (
                    "ChairMan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Meeting",
                "verbose_name_plural": "Work Meeting",
            },
        ),
    ]
